import { Inter } from "next/font/google";
import "./globals.css";
import Homepage from "@/components/Homepage";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BookEase",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Homepage />
      </body>
    </html>
  );
}
